-- ============================================================================
-- MediKiosk — Supabase schema (PostgREST)
-- ============================================================================
-- Run this in the Supabase SQL editor (Dashboard → SQL → New query).
--
-- This replaces the self-hosted Postgres/Redis/MinIO stack with a managed
-- Supabase project. Tables mirror the SQLAlchemy models under
-- backend/app/models/. PHI lives here; file blobs live in Supabase Storage
-- (bucket "medikiosk-documents") — never in the public anon-key path.
--
-- Auth model: the backend authenticates via Clerk (system role runs with the
-- service-role key server-side only). The anon key is NOT granted any table
-- access by default; row-level security (RLS) is enforced so the frontend can
-- never read PHI directly. All writes go through the FastAPI backend.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. EXTENSIONS
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- gen_random_uuid()

-- ============================================================================
-- 2. CLEANUP PREVIOUS SCHEMAS
-- ============================================================================
-- Drop conflicting tables from previous schemas (like mediflow_schema)
DROP TABLE IF EXISTS public.ayush_assessments CASCADE;
DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.red_flag_alerts CASCADE;
DROP TABLE IF EXISTS public.consent_records CASCADE;
DROP TABLE IF EXISTS public.summaries CASCADE;
DROP TABLE IF EXISTS public.documents CASCADE;
DROP TABLE IF EXISTS public.session_messages CASCADE;
DROP TABLE IF EXISTS public.sessions CASCADE;
DROP TABLE IF EXISTS public.patients CASCADE;

-- Drop mediflow specific tables if they exist
DROP TABLE IF EXISTS public.queues CASCADE;
DROP TABLE IF EXISTS public.lab_tests CASCADE;
DROP TABLE IF EXISTS public.prescription_items CASCADE;
DROP TABLE IF EXISTS public.prescriptions CASCADE;
DROP TABLE IF EXISTS public.visits CASCADE;
DROP TABLE IF EXISTS public.opd_slots CASCADE;
DROP TABLE IF EXISTS public.doctors CASCADE;
DROP TABLE IF EXISTS public.departments CASCADE;
DROP TABLE IF EXISTS public.hospitals CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- ============================================================================
-- 3. TABLES (mirror of backend/app/models/)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.patients (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abha_id           varchar(32) UNIQUE,
    aadhaar_hash      varchar(64),            -- SHA-256 of Aadhaar, never raw
    name              varchar(255),
    date_of_birth     date,
    gender            varchar(10),            -- male, female, other, unknown
    phone             varchar(15),
    email             varchar(255),
    address           text,
    language_preference varchar(10) NOT NULL DEFAULT 'hi',
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sessions (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id        bigint REFERENCES public.patients(id),
    kiosk_id          varchar(50),
    department        varchar(50) NOT NULL DEFAULT 'allopathy', -- allopathy, ayurveda, unani, siddha, homeopathy
    language          varchar(10)  NOT NULL DEFAULT 'hi',
    status            varchar(20)  NOT NULL DEFAULT 'in_progress', -- in_progress, completed, under_review, reviewed, cancelled

    chief_complaint    text,
    history_hpi        jsonb,
    past_medical_history jsonb,
    past_surgical_history jsonb,
    drug_history       jsonb,
    allergy_history    jsonb,
    family_history     jsonb,
    personal_history   jsonb,
    review_of_systems  jsonb,
    ayush_assessment   jsonb,

    asr_transcript     text,
    asr_confidence     numeric(4,3),
    llm_raw_response   text,
    confidence_score   numeric(5,2),
    red_flags          jsonb,

    started_at         timestamptz NOT NULL DEFAULT now(),
    completed_at       timestamptz,
    duration_seconds   integer,

    abdm_consent_id    varchar(100),
    fhir_bundle_id     varchar(100),

    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.session_messages (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   bigint NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    message_type varchar(20),   -- ai_question, patient_voice, patient_touch, system
    content      text,
    audio_url    varchar(500),
    confidence   numeric(4,3),
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.documents (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  bigint REFERENCES public.sessions(id) ON DELETE CASCADE,
    patient_id  bigint REFERENCES public.patients(id),

    file_name      varchar(255),
    file_path      varchar(500),          -- Supabase Storage object path
    file_size_bytes integer,
    mime_type      varchar(50),

    document_type  varchar(50),           -- prescription, lab_report, discharge_summary, imaging, insurance, other
    document_date  date,
    hospital_name  varchar(255),
    doctor_name    varchar(255),

    ocr_raw_text   text,
    ocr_confidence numeric(4,3),

    extracted_diagnoses  jsonb,
    extracted_medications jsonb,
    extracted_lab_results jsonb,
    extracted_procedures jsonb,
    extracted_vitals     jsonb,

    processing_status varchar(20) NOT NULL DEFAULT 'pending', -- pending, processing, completed, failed
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.summaries (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   bigint NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    patient_id   bigint REFERENCES public.patients(id),

    summary_text   text,
    summary_format varchar(20) NOT NULL DEFAULT 'structured_text',

    physician_id   bigint,
    physician_edits jsonb,
    review_status  varchar(20) NOT NULL DEFAULT 'pending', -- pending, confirmed, amended, rejected
    reviewed_at    timestamptz,

    fhir_bundle    jsonb,
    pushed_to_abdm boolean NOT NULL DEFAULT false,
    pushed_to_his  boolean NOT NULL DEFAULT false,

    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.consent_records (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   bigint NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    patient_id   bigint REFERENCES public.patients(id),

    consent_type varchar(50),   -- data_capture, his_share, abdm_link, referral_share, research
    granted      boolean NOT NULL DEFAULT false,
    granted_at   timestamptz,
    revoked_at   timestamptz,

    ip_address      varchar(45),
    kiosk_id        varchar(50),
    audio_consent_hash varchar(64),

    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.red_flag_alerts (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   bigint NOT NULL REFERENCES public.sessions(id) ON DELETE CASCADE,
    patient_id   bigint REFERENCES public.patients(id),

    alert_type       varchar(100),  -- chest_pain_mi, stroke, gi_bleed, psychiatric/self-harm, ...
    severity         varchar(20),   -- critical, high, medium
    symptoms_triggered jsonb,
    transcript_snippet text,

    notified_roles  jsonb,
    priority_token  varchar(20),

    created_at  timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    resolved_by varchar(100)
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name   varchar(50),
    record_id    bigint,
    action       varchar(20),  -- CREATE, READ, UPDATE, DELETE
    performed_by varchar(100),
    performed_by_role varchar(50),
    old_values   jsonb,
    new_values   jsonb,
    ip_address   varchar(45),
    user_agent   text,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ayush_assessments (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   bigint NOT NULL UNIQUE REFERENCES public.sessions(id) ON DELETE CASCADE,

    -- Prakriti (constitution)
    prakriti_vata    numeric(3,1),
    prakriti_pitta   numeric(3,1),
    prakriti_kapha   numeric(3,1),
    prakriti_dominant varchar(20),

    -- Vikriti (current imbalance)
    vikriti_vata     numeric(3,1),
    vikriti_pitta    numeric(3,1),
    vikriti_kapha    numeric(3,1),
    vikriti_dominant varchar(20),

    -- Dashavidha Pariksha
    agni_type      varchar(20),
    koshtha_type   varchar(20),
    sara           varchar(20),
    samhanana      varchar(20),
    pramana        varchar(20),
    satmya         text,
    sattva         varchar(20),
    ahara_shakti   varchar(20),
    vyayama_shakti varchar(20),
    vaya           varchar(20),

    nidana     text,
    samprapti  text,

    created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 3. INDEXES (mirror SQLAlchemy index=True columns)
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_patients_abha_id        ON public.patients (abha_id);
CREATE INDEX IF NOT EXISTS idx_sessions_patient_id     ON public.sessions (patient_id);
CREATE INDEX IF NOT EXISTS idx_sessions_kiosk_id       ON public.sessions (kiosk_id);
CREATE INDEX IF NOT EXISTS idx_sessions_status         ON public.sessions (status);
CREATE INDEX IF NOT EXISTS idx_sessions_created_at     ON public.sessions (created_at);
CREATE INDEX IF NOT EXISTS idx_messages_session_id     ON public.session_messages (session_id);
CREATE INDEX IF NOT EXISTS idx_documents_session_id    ON public.documents (session_id);
CREATE INDEX IF NOT EXISTS idx_documents_patient_id    ON public.documents (patient_id);
CREATE INDEX IF NOT EXISTS idx_documents_type          ON public.documents (document_type);
CREATE INDEX IF NOT EXISTS idx_summaries_session_id    ON public.summaries (session_id);
CREATE INDEX IF NOT EXISTS idx_summaries_review_status ON public.summaries (review_status);
CREATE INDEX IF NOT EXISTS idx_consent_session_id      ON public.consent_records (session_id);
CREATE INDEX IF NOT EXISTS idx_red_flag_session_id     ON public.red_flag_alerts (session_id);
CREATE INDEX IF NOT EXISTS idx_red_flag_severity       ON public.red_flag_alerts (severity);
CREATE INDEX IF NOT EXISTS idx_audit_created_at        ON public.audit_logs (created_at);

-- ============================================================================
-- 4. ROW-LEVEL SECURITY
-- ============================================================================
-- Policy model:
--   * The backend runs with the SERVICE_ROLE key -> bypasses RLS entirely,
--     so it can read/write everything it needs.
--   * The anonymous (anon) key is used by the public kiosk ONLY to write
--     consent records and messages via the backend. To keep it safe we still
--     enable RLS and grant the anon role nothing by default — the backend is
--     the only writer. Admin can relax per-table policies later if the
--     frontend must query directly (not recommended for PHI).

ALTER TABLE public.patients           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_messages   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.summaries          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consent_records    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.red_flag_alerts    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ayush_assessments  ENABLE ROW LEVEL SECURITY;

-- Drop default grants so anon cannot touch tables by default (defense in depth).
REVOKE ALL ON public.patients, public.sessions, public.session_messages,
    public.documents, public.summaries, public.consent_records,
    public.red_flag_alerts, public.audit_logs, public.ayush_assessments
    FROM anon, authenticated;

-- The backend (service_role) already bypasses RLS. For completeness, grant it
-- full DML — redundant but explicit.
GRANT SELECT, INSERT, UPDATE, DELETE ON
    public.patients, public.sessions, public.session_messages,
    public.documents, public.summaries, public.consent_records,
    public.red_flag_alerts, public.audit_logs, public.ayush_assessments
    TO service_role;

-- Sequences must be usable by service_role for IDENTITY inserts to work.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

COMMIT;
