"""
ABDM (Ayushman Bharat Digital Mission) integration endpoints.
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Any

from app.database import get_db

router = APIRouter(prefix="/api/v1/abdm", tags=["ABDM Integration"])


@router.post("/verify-abha")
async def verify_abha(
    abha_address: str,
    db: AsyncSession = Depends(get_db),
):
    """
    Verify ABHA address via ABDM Sandbox.
    Mock implementation for the pilot.
    """
    if not abha_address or "@" not in abha_address:
        raise HTTPException(status_code=400, detail="Invalid ABHA address format.")
        
    return {
        "status": "success",
        "abha_address": abha_address,
        "name": "Mock Patient",
        "verified": True
    }


@router.post("/generate-fhir/{session_id}")
async def generate_fhir_bundle(
    session_id: int,
    db: AsyncSession = Depends(get_db),
):
    """
    Generate FHIR R4 Bundle from clinical summary and push to ABDM Sandbox.
    """
    # In reality, we would query the session summary, map it to FHIR resources
    # (Composition, Patient, Encounter, Condition, MedicationStatement)
    # and post to ABDM Gateway.
    
    mock_fhir_bundle = {
        "resourceType": "Bundle",
        "id": f"bundle-{session_id}",
        "type": "document",
        "entry": [
            {
                "fullUrl": "Composition/1",
                "resource": {
                    "resourceType": "Composition",
                    "status": "final",
                    "type": {
                        "coding": [
                            {
                                "system": "http://loinc.org",
                                "code": "11488-4",
                                "display": "Consultation note"
                            }
                        ]
                    },
                    "title": "Clinical Summary generated by MediKiosk"
                }
            }
        ]
    }
    
    return {
        "status": "success",
        "message": "FHIR Bundle generated and pushed to ABDM Gateway",
        "fhir_bundle": mock_fhir_bundle
    }
