import type { UserRole } from '../stores/authStore';

// ─── Detection Helper ──────────────────────────────────────────────
export const isSupabaseConfigured = () => {
  const url = import.meta.env.VITE_SUPABASE_URL || '';
  return url.includes('supabase.co') && !url.includes('your-project');
};

// ─── Helper to get today / offset dates ────────────────────────────
const todayStr = () => new Date().toISOString().split('T')[0];
const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
};
const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
};

// ─── Mock Users ────────────────────────────────────────────────────
export const mockCurrentUser = {
  id: 'mock-user-001',
  email: 'patient@demo.com',
  full_name: 'Rahul Sharma',
  role: 'patient' as UserRole,
  phone: '9876543210',
  avatar_url: null as string | null,
  created_at: '2025-01-01T00:00:00Z',
  updated_at: '2025-01-01T00:00:00Z',
};

export const mockHospitalAdmin = {
  id: 'mock-admin-001',
  email: 'admin@demo.com',
  full_name: 'Dr. Vikram Singh',
  role: 'hospital_admin' as UserRole,
  phone: '9876543211',
  avatar_url: null as string | null,
  hospital_name: 'City General Hospital',
  hospital_address: '45 MG Road, Sector 12, New Delhi 110001',
  hospital_phone: '011-23456789',
  registration_number: 'HOSP-DEL-2024-001',
  created_at: '2025-01-01T00:00:00Z',
  updated_at: '2025-01-01T00:00:00Z',
};

export const mockDoctor = {
  id: 'mock-doctor-001',
  email: 'doctor@demo.com',
  full_name: 'Dr. Priya Mehta',
  role: 'doctor' as UserRole,
  phone: '9876543212',
  avatar_url: null as string | null,
  qualification: 'MD',
  specialization: 'General Medicine',
  license_number: 'MED-12345',
  hospital_id: 'hosp-001',
  created_at: '2025-01-01T00:00:00Z',
  updated_at: '2025-01-01T00:00:00Z',
};

// ─── Mock Hospitals ────────────────────────────────────────────────
export const mockHospitals = [
  {
    id: 'hosp-001',
    name: 'City General Hospital',
    address: '45 MG Road, Sector 12, New Delhi 110001',
    phone: '011-23456789',
    email: 'info@citygeneral.in',
    is_verified: true,
    rating: 4.5,
    total_beds: 200,
    emergency_available: true,
    admin_id: 'mock-admin-001',
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'hosp-002',
    name: 'Sunrise Medical Center',
    address: '12 Park Lane, South Mumbai 400001',
    phone: '022-67890123',
    email: 'info@sunrisemedical.in',
    is_verified: true,
    rating: 4.2,
    total_beds: 120,
    emergency_available: false,
    admin_id: 'mock-admin-002',
    created_at: '2024-08-01T00:00:00Z',
    updated_at: '2024-08-01T00:00:00Z',
  },
];

// ─── Mock Departments ──────────────────────────────────────────────
export const mockDepartments = [
  {
    id: 'dept-001',
    hospital_id: 'hosp-001',
    name: 'General Medicine',
    description: 'Comprehensive primary care and internal medicine services',
    icon: 'stethoscope',
    color: '#6366f1',
    color_code: '#6366f1',
    is_active: true,
    doctor_count: 1,
    patient_count_today: 3,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'dept-002',
    hospital_id: 'hosp-001',
    name: 'Cardiology',
    description: 'Heart and cardiovascular system specialized care',
    icon: 'heart',
    color: '#ef4444',
    color_code: '#ef4444',
    is_active: true,
    doctor_count: 1,
    patient_count_today: 5,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'dept-003',
    hospital_id: 'hosp-001',
    name: 'Orthopedics',
    description: 'Bone, joint, and musculoskeletal system care',
    icon: 'bone',
    color: '#f59e0b',
    color_code: '#f59e0b',
    is_active: true,
    doctor_count: 1,
    patient_count_today: 2,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'dept-004',
    hospital_id: 'hosp-001',
    name: 'Dermatology',
    description: 'Skin, hair, and nail condition treatment',
    icon: 'shield',
    color: '#ec4899',
    color_code: '#ec4899',
    is_active: true,
    doctor_count: 1,
    patient_count_today: 1,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'dept-005',
    hospital_id: 'hosp-001',
    name: 'Pediatrics',
    description: 'Medical care for infants, children, and adolescents',
    icon: 'baby',
    color: '#10b981',
    color_code: '#10b981',
    is_active: true,
    doctor_count: 1,
    patient_count_today: 0,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
];

// ─── Mock Doctors ──────────────────────────────────────────────────
export const mockDoctors = [
  {
    id: 'doc-001',
    user_id: 'mock-doctor-001',
    hospital_id: 'hosp-001',
    department_id: 'dept-001',
    name: 'Priya Mehta',
    full_name: 'Dr. Priya Mehta',
    email: 'doctor@demo.com',
    qualification: 'MD',
    specialization: 'General Medicine',
    license_number: 'MED-12345',
    experience_years: 10,
    consultation_fee: 500,
    avatar_url: null as string | null,
    is_active: true,
    rating: 4.7,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'doc-002',
    user_id: 'mock-doctor-002',
    hospital_id: 'hosp-001',
    department_id: 'dept-002',
    name: 'Arjun Patel',
    full_name: 'Dr. Arjun Patel',
    email: 'arjun@demo.com',
    qualification: 'DM',
    specialization: 'Cardiology',
    license_number: 'MED-12346',
    experience_years: 12,
    consultation_fee: 800,
    avatar_url: null as string | null,
    is_active: true,
    rating: 4.8,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'doc-003',
    user_id: 'mock-doctor-003',
    hospital_id: 'hosp-001',
    department_id: 'dept-003',
    name: 'Suresh Kumar',
    full_name: 'Dr. Suresh Kumar',
    email: 'suresh@demo.com',
    qualification: 'MS',
    specialization: 'Orthopedics',
    license_number: 'MED-12347',
    experience_years: 8,
    consultation_fee: 600,
    avatar_url: null as string | null,
    is_active: true,
    rating: 4.5,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'doc-004',
    user_id: 'mock-doctor-004',
    hospital_id: 'hosp-001',
    department_id: 'dept-004',
    name: 'Neha Gupta',
    full_name: 'Dr. Neha Gupta',
    email: 'neha@demo.com',
    qualification: 'MD',
    specialization: 'Dermatology',
    license_number: 'MED-12348',
    experience_years: 6,
    consultation_fee: 500,
    avatar_url: null as string | null,
    is_active: true,
    rating: 4.6,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'doc-005',
    user_id: 'mock-doctor-005',
    hospital_id: 'hosp-001',
    department_id: 'dept-005',
    name: 'Anita Desai',
    full_name: 'Dr. Anita Desai',
    email: 'anita@demo.com',
    qualification: 'MD',
    specialization: 'Pediatrics',
    license_number: 'MED-12349',
    experience_years: 15,
    consultation_fee: 600,
    avatar_url: null as string | null,
    is_active: true,
    rating: 4.9,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
];

// ─── Mock Patient Record (for patients table) ──────────────────────
export const mockPatientRecord = {
  id: 'mock-user-001',
  name: 'Rahul Sharma',
  email: 'patient@demo.com',
  phone: '9876543210',
  date_of_birth: '1995-03-15',
  gender: 'male',
  address: '123 Gandhi Nagar, Jaipur 302001',
  abha_id: 'ABHA-12345678',
  blood_group: 'B+',
  language_preference: 'en',
  allergies: ['Penicillin'],
  chronic_conditions: [] as string[],
  past_surgeries: [] as string[],
  emergency_contact_name: 'Sunita Sharma',
  emergency_contact_phone: '9876543211',
  created_at: '2024-06-01T00:00:00Z',
  updated_at: '2024-06-01T00:00:00Z',
};

// ─── Mock OPD Slots ────────────────────────────────────────────────
const today = todayStr();
export const mockOpdSlots = [
  { id: 'slot-001', doctor_id: 'doc-001', slot_date: today, slot_time: '09:00', date: today, slot_type: 'morning', start_time: '09:00 AM', end_time: '01:00 PM', is_available: true, max_capacity: 20, max_tokens: 20, current_tokens: 8, patients_booked: 8 },
  { id: 'slot-002', doctor_id: 'doc-001', slot_date: today, slot_time: '09:20', date: today, slot_type: 'morning', start_time: '09:00 AM', end_time: '01:00 PM', is_available: true, max_capacity: 20, max_tokens: 20, current_tokens: 8, patients_booked: 8 },
  { id: 'slot-003', doctor_id: 'doc-001', slot_date: today, slot_time: '09:40', date: today, slot_type: 'morning', start_time: '09:00 AM', end_time: '01:00 PM', is_available: true, max_capacity: 20, max_tokens: 20, current_tokens: 8, patients_booked: 8 },
  { id: 'slot-004', doctor_id: 'doc-001', slot_date: today, slot_time: '10:00', date: today, slot_type: 'morning', start_time: '09:00 AM', end_time: '01:00 PM', is_available: true, max_capacity: 20, max_tokens: 20, current_tokens: 8, patients_booked: 8 },
  { id: 'slot-005', doctor_id: 'doc-001', slot_date: today, slot_time: '10:20', date: today, slot_type: 'morning', start_time: '09:00 AM', end_time: '01:00 PM', is_available: true, max_capacity: 20, max_tokens: 20, current_tokens: 8, patients_booked: 8 },
  { id: 'slot-006', doctor_id: 'doc-001', slot_date: daysFromNow(3), slot_time: '09:00', date: daysFromNow(3), slot_type: 'morning', start_time: '09:00 AM', end_time: '01:00 PM', is_available: true, max_capacity: 20, max_tokens: 20, current_tokens: 3, patients_booked: 3 },
];

// ─── Mock Visits ───────────────────────────────────────────────────
export const mockVisits = [
  {
    id: 'visit-001',
    patient_id: 'mock-user-001',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-001',
    department_name: 'General Medicine',
    doctor_id: 'doc-001',
    doctor_name: 'Dr. Priya Mehta',
    visit_date: daysAgo(60),
    visit_time: '09:20',
    token_number: 'GM-001',
    token: 'GM-001',
    status: 'completed',
    priority: 'normal',
    chief_complaint: 'Fever and body ache for 3 days',
    symptoms_description: 'High grade fever with body ache, mild headache',
    pain_severity: 6,
    associated_symptoms: ['Fever', 'Headache', 'Body Ache'],
    current_medications: null as string | null,
    known_allergies: 'Penicillin',
    vitals: { bp: '120/80', pulse: '98', temperature: '101.2', spo2: '97', weight: '72' },
    diagnosis: 'Viral Fever',
    differential_diagnosis: null as string | null,
    examination_findings: 'Throat congested, mild cervical lymphadenopathy',
    advice: 'Rest, drink plenty of fluids, take paracetamol as needed',
    follow_up_date: daysAgo(46),
    description: 'Patient presented with high-grade fever and generalized body ache for 3 days.',
    triage_notes: null as string | null,
    is_manual_entry: false,
    completed_at: new Date(daysAgo(60)).toISOString(),
    created_at: new Date(daysAgo(60)).toISOString(),
    updated_at: new Date(daysAgo(60)).toISOString(),
  },
  {
    id: 'visit-002',
    patient_id: 'mock-user-001',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-002',
    department_name: 'Cardiology',
    doctor_id: 'doc-002',
    doctor_name: 'Dr. Arjun Patel',
    visit_date: daysAgo(30),
    visit_time: '10:00',
    token_number: 'CARD-007',
    token: 'CARD-007',
    status: 'completed',
    priority: 'urgent',
    chief_complaint: 'Palpitations and mild chest discomfort',
    symptoms_description: 'Intermittent heart palpitations, mild chest tightness on exertion',
    pain_severity: 4,
    associated_symptoms: ['Chest Pain', 'Dizziness'],
    current_medications: null as string | null,
    known_allergies: 'Penicillin',
    vitals: { bp: '138/92', pulse: '88', temperature: '98.4', spo2: '98', weight: '74' },
    diagnosis: 'Hypertension Stage 1',
    differential_diagnosis: null as string | null,
    examination_findings: 'BP elevated, heart rate regular, no murmurs',
    advice: 'Monitor BP daily, reduce salt intake, regular exercise',
    follow_up_date: daysAgo(1),
    description: 'Patient complained of intermittent palpitations.',
    triage_notes: null as string | null,
    is_manual_entry: false,
    completed_at: new Date(daysAgo(30)).toISOString(),
    created_at: new Date(daysAgo(30)).toISOString(),
    updated_at: new Date(daysAgo(30)).toISOString(),
  },
  {
    id: 'visit-003',
    patient_id: 'mock-user-001',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-004',
    department_name: 'Dermatology',
    doctor_id: 'doc-004',
    doctor_name: 'Dr. Neha Gupta',
    visit_date: daysAgo(21),
    visit_time: '11:00',
    token_number: 'DERM-012',
    token: 'DERM-012',
    status: 'completed',
    priority: 'normal',
    chief_complaint: 'Persistent skin rash on forearms',
    symptoms_description: 'Itchy red patches on both forearms for 2 weeks',
    pain_severity: 3,
    associated_symptoms: ['Skin Rash'],
    current_medications: null as string | null,
    known_allergies: 'Penicillin',
    vitals: { bp: '118/76', pulse: '72', temperature: '98.6', spo2: '99', weight: '72' },
    diagnosis: 'Eczema',
    differential_diagnosis: null as string | null,
    examination_findings: 'Erythematous patches with mild scaling on bilateral forearms',
    advice: 'Apply moisturizer regularly, avoid harsh soaps, use prescribed cream',
    follow_up_date: null as string | null,
    description: 'Chronic eczema flare-up on forearms.',
    triage_notes: null as string | null,
    is_manual_entry: false,
    completed_at: new Date(daysAgo(21)).toISOString(),
    created_at: new Date(daysAgo(21)).toISOString(),
    updated_at: new Date(daysAgo(21)).toISOString(),
  },
  {
    id: 'visit-004',
    patient_id: 'mock-user-001',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-002',
    department_name: 'Cardiology',
    doctor_id: 'doc-002',
    doctor_name: 'Dr. Arjun Patel',
    visit_date: today,
    visit_time: '09:00',
    token_number: 'CARD-042',
    token: 'CARD-042',
    status: 'in_queue',
    priority: 'urgent',
    chief_complaint: 'Chest pain since morning',
    symptoms_description: 'Sharp chest pain on left side, started 3 hours ago',
    pain_severity: 7,
    associated_symptoms: ['Chest Pain', 'Shortness of Breath'],
    current_medications: null as string | null,
    known_allergies: 'Penicillin',
    vitals: { bp: '142/94', pulse: '96', temperature: '98.2', spo2: '96', weight: '74' },
    diagnosis: null as string | null,
    differential_diagnosis: null as string | null,
    examination_findings: null as string | null,
    advice: null as string | null,
    follow_up_date: null as string | null,
    description: 'Acute onset chest pain.',
    triage_notes: 'Urgent - possible cardiac. ECG recommended.',
    is_manual_entry: false,
    completed_at: null as string | null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'visit-005',
    patient_id: 'mock-user-001',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-001',
    department_name: 'General Medicine',
    doctor_id: 'doc-001',
    doctor_name: 'Dr. Priya Mehta',
    visit_date: daysFromNow(3),
    visit_time: '10:00',
    token_number: 'GM-018',
    token: 'GM-018',
    status: 'booked',
    priority: 'normal',
    chief_complaint: 'Persistent cough for 1 week',
    symptoms_description: 'Dry cough, worse at night, no fever',
    pain_severity: 2,
    associated_symptoms: ['Cough'],
    current_medications: null as string | null,
    known_allergies: 'Penicillin',
    vitals: null as Record<string, string | null> | null,
    diagnosis: null as string | null,
    differential_diagnosis: null as string | null,
    examination_findings: null as string | null,
    advice: null as string | null,
    follow_up_date: null as string | null,
    description: 'Persistent dry cough for 1 week.',
    triage_notes: null as string | null,
    is_manual_entry: false,
    completed_at: null as string | null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ─── Mock Hospital Visits (for hospital dashboard - richer set) ────
export const mockHospitalVisits = [
  ...mockVisits.filter(v => v.visit_date === today),
  {
    id: 'visit-h001',
    patient_id: 'mock-patient-002',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-002',
    department_name: 'Cardiology',
    doctor_id: 'doc-002',
    doctor_name: 'Dr. Arjun Patel',
    visit_date: today,
    visit_time: '09:00',
    token_number: 'CARD-043',
    token: 'CARD-043',
    status: 'completed',
    priority: 'normal',
    chief_complaint: 'Follow-up for hypertension',
    symptoms_description: null as string | null,
    pain_severity: null as number | null,
    associated_symptoms: null as string[] | null,
    current_medications: null as string | null,
    known_allergies: null as string | null,
    vitals: { bp: '130/85', pulse: '76', temperature: '98.4', spo2: '98', weight: '68' },
    diagnosis: 'Hypertension - well controlled',
    differential_diagnosis: null as string | null,
    examination_findings: null as string | null,
    advice: 'Continue current medication',
    follow_up_date: daysFromNow(30),
    description: null as string | null,
    triage_notes: null as string | null,
    is_manual_entry: false,
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'visit-h002',
    patient_id: 'mock-patient-003',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-001',
    department_name: 'General Medicine',
    doctor_id: 'doc-001',
    doctor_name: 'Dr. Priya Mehta',
    visit_date: today,
    visit_time: '09:20',
    token_number: 'GM-019',
    token: 'GM-019',
    status: 'with_doctor',
    priority: 'normal',
    chief_complaint: 'Cold and sore throat',
    symptoms_description: null as string | null,
    pain_severity: 3,
    associated_symptoms: ['Cough', 'Fever'],
    current_medications: null as string | null,
    known_allergies: null as string | null,
    vitals: { bp: '118/76', pulse: '82', temperature: '99.1', spo2: '98', weight: '55' },
    diagnosis: null as string | null,
    differential_diagnosis: null as string | null,
    examination_findings: null as string | null,
    advice: null as string | null,
    follow_up_date: null as string | null,
    description: null as string | null,
    triage_notes: null as string | null,
    is_manual_entry: false,
    completed_at: null as string | null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'visit-h003',
    patient_id: 'mock-patient-004',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-001',
    department_name: 'General Medicine',
    doctor_id: 'doc-001',
    doctor_name: 'Dr. Priya Mehta',
    visit_date: today,
    visit_time: '09:40',
    token_number: 'GM-020',
    token: 'GM-020',
    status: 'in_queue',
    priority: 'urgent',
    chief_complaint: 'Severe abdominal pain',
    symptoms_description: null as string | null,
    pain_severity: 8,
    associated_symptoms: ['Nausea', 'Vomiting'],
    current_medications: null as string | null,
    known_allergies: null as string | null,
    vitals: { bp: '110/70', pulse: '100', temperature: '99.8', spo2: '97', weight: '62' },
    diagnosis: null as string | null,
    differential_diagnosis: null as string | null,
    examination_findings: null as string | null,
    advice: null as string | null,
    follow_up_date: null as string | null,
    description: null as string | null,
    triage_notes: null as string | null,
    is_manual_entry: false,
    completed_at: null as string | null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'visit-h004',
    patient_id: 'mock-patient-005',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-003',
    department_name: 'Orthopedics',
    doctor_id: 'doc-003',
    doctor_name: 'Dr. Suresh Kumar',
    visit_date: today,
    visit_time: '09:00',
    token_number: 'ORT-008',
    token: 'ORT-008',
    status: 'completed',
    priority: 'normal',
    chief_complaint: 'Knee pain for 2 weeks',
    symptoms_description: null as string | null,
    pain_severity: 5,
    associated_symptoms: ['Joint Pain', 'Swelling'],
    current_medications: null as string | null,
    known_allergies: null as string | null,
    vitals: { bp: '122/78', pulse: '74', temperature: '98.4', spo2: '99', weight: '80' },
    diagnosis: 'Osteoarthritis - mild',
    differential_diagnosis: null as string | null,
    examination_findings: null as string | null,
    advice: 'Knee exercise, hot fomentation, avoid heavy lifting',
    follow_up_date: daysFromNow(14),
    description: null as string | null,
    triage_notes: null as string | null,
    is_manual_entry: false,
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'visit-h005',
    patient_id: 'mock-patient-006',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-003',
    department_name: 'Orthopedics',
    doctor_id: 'doc-003',
    doctor_name: 'Dr. Suresh Kumar',
    visit_date: today,
    visit_time: '09:20',
    token_number: 'ORT-009',
    token: 'ORT-009',
    status: 'waiting',
    priority: 'normal',
    chief_complaint: 'Lower back pain',
    symptoms_description: null as string | null,
    pain_severity: 4,
    associated_symptoms: ['Body Ache'],
    current_medications: null as string | null,
    known_allergies: null as string | null,
    vitals: { bp: '124/82', pulse: '70', temperature: '98.6', spo2: '99', weight: '65' },
    diagnosis: null as string | null,
    differential_diagnosis: null as string | null,
    examination_findings: null as string | null,
    advice: null as string | null,
    follow_up_date: null as string | null,
    description: null as string | null,
    triage_notes: null as string | null,
    is_manual_entry: false,
    completed_at: null as string | null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'visit-h006',
    patient_id: 'mock-patient-007',
    hospital_id: 'hosp-001',
    hospital_name: 'City General Hospital',
    department_id: 'dept-004',
    department_name: 'Dermatology',
    doctor_id: 'doc-004',
    doctor_name: 'Dr. Neha Gupta',
    visit_date: today,
    visit_time: '10:00',
    token_number: 'DERM-013',
    token: 'DERM-013',
    status: 'booked',
    priority: 'normal',
    chief_complaint: 'Acne breakout on face',
    symptoms_description: null as string | null,
    pain_severity: 2,
    associated_symptoms: ['Skin Rash'],
    current_medications: null as string | null,
    known_allergies: null as string | null,
    vitals: null as Record<string, string | null> | null,
    diagnosis: null as string | null,
    differential_diagnosis: null as string | null,
    examination_findings: null as string | null,
    advice: null as string | null,
    follow_up_date: null as string | null,
    description: null as string | null,
    triage_notes: null as string | null,
    is_manual_entry: false,
    completed_at: null as string | null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ─── Mock Patients (for hospital/doctor joins) ─────────────────────
export const mockPatients = [
  { id: 'mock-user-001', name: 'Rahul Sharma', email: 'patient@demo.com', phone: '9876543210', date_of_birth: '1995-03-15', gender: 'male', abha_id: 'ABHA-12345678', blood_group: 'B+', language_preference: 'en', allergies: ['Penicillin'], chronic_conditions: [], past_surgeries: [], created_at: '2024-06-01T00:00:00Z', updated_at: '2024-06-01T00:00:00Z' },
  { id: 'mock-patient-002', name: 'Amit Kumar', email: 'amit@demo.com', phone: '9876543220', date_of_birth: '1988-07-20', gender: 'male', abha_id: null, blood_group: 'A+', language_preference: 'en', allergies: [], chronic_conditions: ['Hypertension'], past_surgeries: [], created_at: '2024-06-01T00:00:00Z', updated_at: '2024-06-01T00:00:00Z' },
  { id: 'mock-patient-003', name: 'Sneha Reddy', email: 'sneha@demo.com', phone: '9876543230', date_of_birth: '2000-11-05', gender: 'female', abha_id: null, blood_group: 'O+', language_preference: 'hi', allergies: [], chronic_conditions: [], past_surgeries: [], created_at: '2024-06-01T00:00:00Z', updated_at: '2024-06-01T00:00:00Z' },
  { id: 'mock-patient-004', name: 'Rajesh Verma', email: 'rajesh@demo.com', phone: '9876543240', date_of_birth: '1975-02-28', gender: 'male', abha_id: null, blood_group: 'AB+', language_preference: 'en', allergies: ['Ibuprofen'], chronic_conditions: ['Diabetes Type 2'], past_surgeries: ['Appendectomy'], created_at: '2024-06-01T00:00:00Z', updated_at: '2024-06-01T00:00:00Z' },
  { id: 'mock-patient-005', name: 'Priyanka Joshi', email: 'priyanka@demo.com', phone: '9876543250', date_of_birth: '1992-09-12', gender: 'female', abha_id: null, blood_group: 'B-', language_preference: 'en', allergies: [], chronic_conditions: [], past_surgeries: [], created_at: '2024-06-01T00:00:00Z', updated_at: '2024-06-01T00:00:00Z' },
  { id: 'mock-patient-006', name: 'Manoj Singh', email: 'manoj@demo.com', phone: '9876543260', date_of_birth: '1980-05-01', gender: 'male', abha_id: null, blood_group: 'O-', language_preference: 'hi', allergies: [], chronic_conditions: [], past_surgeries: [], created_at: '2024-06-01T00:00:00Z', updated_at: '2024-06-01T00:00:00Z' },
  { id: 'mock-patient-007', name: 'Ananya Das', email: 'ananya@demo.com', phone: '9876543270', date_of_birth: '1998-12-18', gender: 'female', abha_id: null, blood_group: 'A-', language_preference: 'en', allergies: [], chronic_conditions: [], past_surgeries: [], created_at: '2024-06-01T00:00:00Z', updated_at: '2024-06-01T00:00:00Z' },
];

// ─── Mock Documents ────────────────────────────────────────────────
export const mockDocuments = [
  {
    id: 'doc-rec-001',
    session_id: null as number | null,
    patient_id: 'mock-user-001',
    file_name: 'Prescription_GM-001.pdf',
    file_size_bytes: 45200,
    mime_type: 'application/pdf',
    document_type: 'prescription' as const,
    document_date: daysAgo(60),
    hospital_name: 'City General Hospital',
    doctor_name: 'Dr. Priya Mehta',
    ocr_raw_text: null as string | null,
    ocr_confidence: null as number | null,
    extracted_diagnoses: null as Record<string, unknown> | null,
    extracted_medications: null as Record<string, unknown> | null,
    extracted_lab_results: null as Record<string, unknown> | null,
    extracted_procedures: null as Record<string, unknown> | null,
    extracted_vitals: null as Record<string, unknown> | null,
    processing_status: 'completed' as const,
    created_at: new Date(daysAgo(60)).toISOString(),
  },
  {
    id: 'doc-rec-002',
    session_id: null as number | null,
    patient_id: 'mock-user-001',
    file_name: 'Prescription_CARD-007.pdf',
    file_size_bytes: 38900,
    mime_type: 'application/pdf',
    document_type: 'prescription' as const,
    document_date: daysAgo(30),
    hospital_name: 'City General Hospital',
    doctor_name: 'Dr. Arjun Patel',
    ocr_raw_text: null as string | null,
    ocr_confidence: null as number | null,
    extracted_diagnoses: null as Record<string, unknown> | null,
    extracted_medications: null as Record<string, unknown> | null,
    extracted_lab_results: null as Record<string, unknown> | null,
    extracted_procedures: null as Record<string, unknown> | null,
    extracted_vitals: null as Record<string, unknown> | null,
    processing_status: 'completed' as const,
    created_at: new Date(daysAgo(30)).toISOString(),
  },
  {
    id: 'doc-rec-003',
    session_id: null as number | null,
    patient_id: 'mock-user-001',
    file_name: 'Lipid_Profile_Report.pdf',
    file_size_bytes: 128000,
    mime_type: 'application/pdf',
    document_type: 'lab_report' as const,
    document_date: daysAgo(30),
    hospital_name: 'City General Hospital',
    doctor_name: 'Dr. Arjun Patel',
    ocr_raw_text: null as string | null,
    ocr_confidence: null as number | null,
    extracted_diagnoses: null as Record<string, unknown> | null,
    extracted_medications: null as Record<string, unknown> | null,
    extracted_lab_results: null as Record<string, unknown> | null,
    extracted_procedures: null as Record<string, unknown> | null,
    extracted_vitals: null as Record<string, unknown> | null,
    processing_status: 'completed' as const,
    created_at: new Date(daysAgo(30)).toISOString(),
  },
  {
    id: 'doc-rec-004',
    session_id: null as number | null,
    patient_id: 'mock-user-001',
    file_name: 'Chest_Xray_Report.jpg',
    file_size_bytes: 256000,
    mime_type: 'image/jpeg',
    document_type: 'imaging' as const,
    document_date: daysAgo(21),
    hospital_name: 'City General Hospital',
    doctor_name: 'Dr. Neha Gupta',
    ocr_raw_text: null as string | null,
    ocr_confidence: null as number | null,
    extracted_diagnoses: null as Record<string, unknown> | null,
    extracted_medications: null as Record<string, unknown> | null,
    extracted_lab_results: null as Record<string, unknown> | null,
    extracted_procedures: null as Record<string, unknown> | null,
    extracted_vitals: null as Record<string, unknown> | null,
    processing_status: 'completed' as const,
    created_at: new Date(daysAgo(21)).toISOString(),
  },
];

// ─── Mock Prescriptions ────────────────────────────────────────────
export const mockPrescriptions = [
  {
    id: 'rx-001',
    visit_id: 'visit-001',
    patient_id: 'mock-user-001',
    doctor_id: 'doc-001',
    created_at: new Date(daysAgo(60)).toISOString(),
    prescription_items: [
      { drug_name: 'Paracetamol 500mg', dosage: '500mg', frequency: 'three_times_daily', duration: '5_days', instructions: 'After food' },
      { drug_name: 'Cetirizine 10mg', dosage: '10mg', frequency: 'once_daily', duration: '5_days', instructions: 'At bedtime' },
    ],
  },
  {
    id: 'rx-002',
    visit_id: 'visit-002',
    patient_id: 'mock-user-001',
    doctor_id: 'doc-002',
    created_at: new Date(daysAgo(30)).toISOString(),
    prescription_items: [
      { drug_name: 'Amlodipine 5mg', dosage: '5mg', frequency: 'once_daily', duration: '1_month', instructions: 'Morning, after food' },
      { drug_name: 'Metformin 500mg', dosage: '500mg', frequency: 'twice_daily', duration: '1_month', instructions: 'With meals' },
    ],
  },
];

// ─── Mock Queue Entries (for hospital admin) ───────────────────────
const now = new Date();
const queuedTime = (minutesAgo: number) => {
  const d = new Date(now.getTime() - minutesAgo * 60000);
  return d.toISOString();
};

export const mockQueueEntries: Record<string, Array<{
  id: number;
  visit_id: string;
  token: string;
  patient_name: string;
  priority: string;
  status: string;
  queued_at: string;
  called_at: string | null;
  hospital_id: string;
  department_id: string;
  department_name: string;
  queue_date: string;
}>> = {
  'dept-001': [
    { id: 1, visit_id: 'visit-h003', token: 'GM-020', patient_name: 'Rajesh Verma', priority: 'urgent', status: 'waiting', queued_at: queuedTime(15), called_at: null, hospital_id: 'hosp-001', department_id: 'dept-001', department_name: 'General Medicine', queue_date: today },
    { id: 2, visit_id: 'visit-h002', token: 'GM-019', patient_name: 'Sneha Reddy', priority: 'normal', status: 'in_consultation', queued_at: queuedTime(35), called_at: queuedTime(25), hospital_id: 'hosp-001', department_id: 'dept-001', department_name: 'General Medicine', queue_date: today },
    { id: 3, visit_id: 'visit-h001', token: 'GM-019', patient_name: 'Amit Kumar', priority: 'normal', status: 'completed', queued_at: queuedTime(55), called_at: queuedTime(45), hospital_id: 'hosp-001', department_id: 'dept-001', department_name: 'General Medicine', queue_date: today },
  ],
  'dept-002': [
    { id: 4, visit_id: 'visit-004', token: 'CARD-042', patient_name: 'Rahul Sharma', priority: 'urgent', status: 'called', queued_at: queuedTime(20), called_at: queuedTime(5), hospital_id: 'hosp-001', department_id: 'dept-002', department_name: 'Cardiology', queue_date: today },
    { id: 5, visit_id: 'visit-h001b', token: 'CARD-043', patient_name: 'Amit Kumar', priority: 'normal', status: 'completed', queued_at: queuedTime(60), called_at: queuedTime(50), hospital_id: 'hosp-001', department_id: 'dept-002', department_name: 'Cardiology', queue_date: today },
  ],
  'dept-003': [
    { id: 6, visit_id: 'visit-h005', token: 'ORT-009', patient_name: 'Manoj Singh', priority: 'normal', status: 'waiting', queued_at: queuedTime(10), called_at: null, hospital_id: 'hosp-001', department_id: 'dept-003', department_name: 'Orthopedics', queue_date: today },
    { id: 7, visit_id: 'visit-h004', token: 'ORT-008', patient_name: 'Priyanka Joshi', priority: 'normal', status: 'completed', queued_at: queuedTime(45), called_at: queuedTime(35), hospital_id: 'hosp-001', department_id: 'dept-003', department_name: 'Orthopedics', queue_date: today },
  ],
  'dept-004': [
    { id: 8, visit_id: 'visit-h006', token: 'DERM-013', patient_name: 'Ananya Das', priority: 'normal', status: 'waiting', queued_at: queuedTime(5), called_at: null, hospital_id: 'hosp-001', department_id: 'dept-004', department_name: 'Dermatology', queue_date: today },
  ],
  'dept-005': [],
};

// ─── Mock Queue Statuses (for hospital dashboard) ──────────────────
export const mockQueueStatuses = [
  { department_name: 'General Medicine', current_token: 20, waiting_count: 1 },
  { department_name: 'Cardiology', current_token: 42, waiting_count: 0 },
  { department_name: 'Orthopedics', current_token: 9, waiting_count: 1 },
  { department_name: 'Dermatology', current_token: 13, waiting_count: 1 },
  { department_name: 'Pediatrics', current_token: 0, waiting_count: 0 },
];

// ─── Mock Doctor's Today Visits (for doctor portal) ────────────────
export const mockDoctorTodayVisits = [
  {
    id: 'visit-004',
    token_number: 42,
    patient_id: 'mock-user-001',
    chief_complaint: 'Chest pain since morning',
    priority: 'urgent',
    status: 'in_progress',
    queued_at: queuedTime(20),
    visit_date: today,
    doctor_id: 'doc-001',
    patients: { name: 'Rahul Sharma', date_of_birth: '1995-03-15', gender: 'male', phone: '9876543210' },
  },
  {
    id: 'visit-h002',
    token_number: 19,
    patient_id: 'mock-patient-003',
    chief_complaint: 'Cold and sore throat',
    priority: 'normal',
    status: 'completed',
    queued_at: queuedTime(50),
    visit_date: today,
    doctor_id: 'doc-001',
    patients: { name: 'Sneha Reddy', date_of_birth: '2000-11-05', gender: 'female', phone: '9876543230' },
  },
  {
    id: 'visit-h003',
    token_number: 20,
    patient_id: 'mock-patient-004',
    chief_complaint: 'Severe abdominal pain',
    priority: 'urgent',
    status: 'waiting',
    queued_at: queuedTime(10),
    visit_date: today,
    doctor_id: 'doc-001',
    patients: { name: 'Rajesh Verma', date_of_birth: '1975-02-28', gender: 'male', phone: '9876543240' },
  },
];

// ─── Mock Doctor Full Visit Data (for PatientCard) ─────────────────
export const mockDoctorFullVisit = {
  id: 'visit-004',
  patient_id: 'mock-user-001',
  hospital_id: 'hosp-001',
  department_id: 'dept-002',
  department_name: 'Cardiology',
  doctor_id: 'doc-001',
  doctor_name: 'Dr. Priya Mehta',
  visit_date: today,
  visit_time: '09:00',
  token_number: 42,
  token: 'CARD-042',
  status: 'in_progress',
  priority: 'urgent',
  chief_complaint: 'Chest pain since morning',
  symptoms_description: 'Sharp chest pain on left side, started 3 hours ago, radiating to left arm',
  severity: 7,
  associated_symptoms: ['Chest Pain', 'Shortness of Breath', 'Dizziness'],
  current_medications: ['Amlodipine 5mg'],
  allergies: 'Penicillin',
  vitals: { bp: '142/94', pulse: '96', temperature: '98.2', spo2: '96', weight: '74' },
  diagnosis: null as string | null,
  differential_diagnosis: null as string | null,
  examination_findings: null as string | null,
  advice: null as string | null,
  follow_up_date: null as string | null,
  completed_at: null as string | null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  patients: mockPatients[0],
  doctors: { name: 'Priya Mehta' },
};

// ─── Mock Past Visits (for doctor PatientCard) ─────────────────────
export const mockPastVisits = [
  { id: 'visit-001', visit_date: daysAgo(60), diagnosis: 'Viral Fever', doctor_name: 'Priya Mehta', department: 'General Medicine' },
  { id: 'visit-002', visit_date: daysAgo(30), diagnosis: 'Hypertension Stage 1', doctor_name: 'Arjun Patel', department: 'Cardiology' },
  { id: 'visit-003', visit_date: daysAgo(21), diagnosis: 'Eczema', doctor_name: 'Neha Gupta', department: 'Dermatology' },
];

// ─── Mock Diagnosis List ───────────────────────────────────────────
export const mockDiagnosis = [
  'Viral Fever',
  'Bacterial Infection',
  'Common Cold',
  'Influenza',
  'Hypertension Stage 1',
  'Hypertension Stage 2',
  'Type 2 Diabetes Mellitus',
  'Hypothyroidism',
  'Hyperthyroidism',
  'Eczema',
  'Psoriasis',
  'Contact Dermatitis',
  'Acne Vulgaris',
  'Migraine',
  'Tension Headache',
  ' GERD',
  'Irritable Bowel Syndrome',
  'Osteoarthritis',
  'Rheumatoid Arthritis',
  'Lower Back Pain',
  'Cervical Spondylosis',
  'Asthma',
  'Bronchitis',
  'Pneumonia',
  'Anemia',
  'Vitamin D Deficiency',
  'UTI',
  'Allergic Rhinitis',
  'Anxiety Disorder',
  'Depression',
];

// ─── Mock Pharmacy Drugs ───────────────────────────────────────────
export const mockPharmacyDrugs = [
  'Paracetamol 500mg',
  'Amoxicillin 250mg',
  'Metformin 500mg',
  'Amlodipine 5mg',
  'Omeprazole 20mg',
  'Cetirizine 10mg',
  'Ibuprofen 400mg',
  'Azithromycin 500mg',
  'Vitamin D3 1000IU',
  'Iron + Folic Acid',
  'Atorvastatin 10mg',
  'Metoprolol 25mg',
  'Losartan 50mg',
  'Pantoprazole 40mg',
  'Montelukast 10mg',
  'Dolo 650',
  'Pan-D',
  'Telmisartan 40mg',
  'Glimepiride 2mg',
  'Levocetirizine 5mg',
  'Doxycycline 100mg',
  'Pantop D',
  'Metformin SR 500mg',
  'Atenolol 50mg',
  'Aspirin 75mg',
];

// ─── Mock Doctor Profile (for doctor portal) ───────────────────────
export const mockDoctorProfile = {
  id: 'doc-001',
  name: 'Priya Mehta',
  full_name: 'Dr. Priya Mehta',
  user_id: 'mock-doctor-001',
  specialization: 'General Medicine',
  department: 'General Medicine',
  email: 'doctor@demo.com',
  qualification: 'MD',
  license_number: 'MED-12345',
  hospital_id: 'hosp-001',
  is_active: true,
  created_at: '2024-06-01T00:00:00Z',
  updated_at: '2024-06-01T00:00:00Z',
};
